---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
    app.kubernetes.io/instance: echoserver
spec:
  selector:
    app.kubernetes.io/name: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
