---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-manifest-aoa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
                    revision: HEAD
                    files:
                      - path: envs/sit/apps-config.yaml
                - list:
                    elementsYaml: "{{ .k8s_manifest_apps | toJson }}"
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
                    revision: HEAD
                    files:
                      - path: envs/sit/apps-config.yaml
                - list:
                    elementsYaml: "{{ .common_params | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      labels:
        custom.label/deployed-by: "k8s-manifests-aoa"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'sit'
      sources:
        - repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
          targetRevision: HEAD
          path: apps/{{.config_dir}}
          directory:
            recurse: true
        - repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
          targetRevision: HEAD
          path: envs/sit/{{.config_dir}}
          directory:
            recurse: true
      destination:
        name: sit
        namespace: "{{.namespace}}"
      info:
        - name: 'Applicatation url:'
          value: "http://{{.name}}.sit.example.com"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true