global:
  domain: localhost:8080
  additionalLabels:
    environment: dev
configs:
  cm:
    passwordPattern: "^.{4,32}$"
    url: 'http://localhost:8080/'
    statusbadge.url: 'http://localhost:8080/'
    accounts.oisis: apiKey, login
    accounts.oisis.enabled: true
  rbac:
    policy.csv: |
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, applicationsets, get, */*, allow
      p, role:readonly, projects, get, */*, allow
      p, role:readonly, repositories, get, */*, allow
      p, role:readonly, clusters, get, */*, allow
      p, role:readonly, exec, create, */*, deny
      p, role:readonly, logs, get, */*, allow
      p, role:admin, *, *, */*, allow
      g, admin, role:admin
      g, oisis, role:readonly
    policy.default: role:readonly
  secret:
    extra:
      # HOWTO: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-secret.yaml
      # To generate password run command: htpasswd -nbBC 10 "" admin123 | tr -d ':\n' | sed 's/$2y/$2a/'
      # oisis password: oisis
      accounts.oisis.password: $2a$10$/GN2Nnl2WGQnjOnFLgzBn.1B2o.fIa7RQkAcqvwgTL4/Ai1xU2tui
      # admin password: admin
      admin.password: $2a$10$WeVnTGLH/oq1XSuVIkGj6udjNQmizKhZyeuLKClTz.KLkvwaO.T0a
