global:
  domain: localhost:8080
  additionalLabels:
    environment: dev
configs:
  accounts.oisis: apiKey, login
  rbac:
    policy.csv: |
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, applicationsets, get, */*, allow
      p, role:readonly, projects, get, */*, allow
      p, role:readonly, repositories, get, */*, allow
      p, role:readonly, clusters, get, */*, allow
      p, role:readonly, exec, create, */*, deny
      p, role:readonly, logs, get, */*, allow
      g, oisis, role:readonly
