global:
  domain: localhost:8080
  additionalLabels:
    environment: dev
configs:
  cm:
    passwordPattern: "^.{4,32}$"
    url: 'http://localhost:8080/'
    statusbadge.url: 'http://localhost:8080/'
    accounts.oisis: apiKey, login
    accounts.oisis.enabled: true
  rbac:
    policy.csv: |
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, applicationsets, get, */*, allow
      p, role:readonly, projects, get, */*, allow
      p, role:readonly, repositories, get, */*, allow
      p, role:readonly, clusters, get, */*, allow
      p, role:readonly, exec, create, */*, deny
      p, role:readonly, logs, get, */*, allow
      g, oisis, role:readonly
  secret:
    extra:
      # HOWTO: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-secret.yaml
      # To generate password run command: htpasswd -nbBC 10 "" admin123 | tr -d ':\n' | sed 's/$2y/$2a/'
      # oisis password: password
      accounts.oisis.password: $2a$10$fHU2qAD5fd5qKqMRfHZ4/.Cj2iE3WzK.vmWvR94Fu.41h46u6rbBm
      # admin password: admin123
      admin.password: $2a$10$0xHOSiR5ZPwcnzDGKSe/1e.A0hBRW7kuokefJa4e17ugOLmK0/aAK
