image:
  debug: false
replicaCount: 1
updateStrategy:
  type: RollingUpdate
tls:
  enabled: false
containerPorts:
  http: 1080
  https: 1443
resourcesPreset: "nano"
autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPU: ""
  targetMemory: ""
service:
  type: ClusterIP