---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-manifest-aoa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
          revision: HEAD
          files:
            - path: envs/dev/k8s-manifest-apps.yaml
      - list:
          elementsYaml: "{{ .appconfig | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      labels:
        custom.label/deployed-by: "k8s-manifests-aoa"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'dev'
      sources:
        - repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
          targetRevision: HEAD
          path: apps/{{.config_dir}}
          directory:
            recurse: true
        - repoURL: https://github.com/oisis/ArgoCD-multienv-example.git
          targetRevision: HEAD
          path: envs/dev/{{.config_dir}}
          directory:
            recurse: true
      destination:
        name: dev
        namespace: "{{.namespace}}"
      info:
        - name: 'Applicatation url:'
          value: "http://{{.name}}.dev.example.com"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true