---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-user-oisis
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.oisis: apiKey, login
  accounts.oisis.enabled: "enable"