common_params:
  - environment: dev
    domain: "dev.example.com"
helm_apps:
  - name: "nginx"
    namespace: "nginx"
    project: "dev"
    repoUrl: "https://charts.bitnami.com/bitnami"
    chart: nginx
    targetRevision: "18.2.5"
k8s_manifest_apps:
  - name: "echoserver2"
    namespace: "echoserver2"
    config_dir: "echoserver2"
